[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000

fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read", path = "../euler-interfaces" },
]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
wrap_comments = true
ignore = [
    "script/clusters/*"
]

[profile.default.lint]
severity = ["high", "med"]